export const environment = {
  production: true,
  appVersion: 'v1.0.0.3',
  isMockEnabled: true,
  USERDATA_KEY: 'authf649fc9a5f55',
  authApi: 'http://angularegitim.com/kullanici/login',
  makinalarApi: 'http://localhost:8080/makina/makinalar',
  remmakinalarApi: 'http://localhost:8080/makina/delete',
  remmusterilerApi: 'http://localhost:8080/musteri/delete',
  musterilerApi: 'http://localhost:8080/musteri/musteriler',
  bakimplanApi: 'http://localhost:8080/bakimplan/bakimplanlar',
  rembakimplanApi: 'http://localhost:8080/bakimplan/delete',
  reportsApi:'http://localhost:8080/api/reports',


  rolesApi: 'http://angularegitim.com/api/app-roles',
  appRoleObjectsApi: 'http://angularegitim.com/api/app-role-objects',
  usersApi:'http://angularegitim.com/api/users',
  lookUpsApi:'http://angularegitim.com/api/look-ups',
  dashboardApi:'http://angularegitim.com/api/dashboard',
  customersApi:'http://angularegitim.com/api/customers',
  booksApi:'http://angularegitim.com/api/books',
  epcReadingsApi:'http://angularegitim.com/api/epc-readings',
  studentsApi:'http://angularegitim.com/api/students',
  debitsApi:'http://angularegitim.com/api/student-books',
  alarmsApi:'http://angularegitim.com/api/alarms',
};
